### ISSUE TITLE
THIS IS sPARTA

### ISSUE THREAD

**Issue by MatthewRalston** [atulkakrana/sPARTA.github#10]
This isn't actually an issue... I just couldn't resist. Closing. :)

![What this is](http://i2.kym-cdn.com/photos/images/newsfeed/000/010/859/300x15.jpg)

**Comment by atulkakrana** [comment]
The bug is closed "officially" only after I review the solution and close it. I am glad the "friendly peek" issue got resolved so fast :) 

Atul
