### ISSUE TITLE
An error"Argument ">TamiR8064%0AGCCAACTGAGCTATTCCAGC%0" isn't numeric in bitwise and (&) at /data1/masw/bowtie2-2.3.1-legacy/bowtie2 line 551"

### ISSUE THREAD

**Issue by shenweima** [atulkakrana/sPARTA.github#4]
My command
`python3 sPARTA.py -genomeFile IWGSCv1.fa -annoType GTF -annoFile transctipts_merged.gtf -genomeFeature 0 -miRNAFile miRNA.fa -libs SRR1197125.chopped.trimmed.processed.txt SRR1197126.chopped.trimmed.processed.txt -tarPred H -tarScore N --tag2FASTA --map2DD --validate -minTagLen 18 -accel 10
An error:
Total time for backward call to driver() for mirror index: 00:01:43
Predicting targets for frag:genomic_seq.frag.20.fa using index:./index/genomic_seq.frag.20.fa_index
You chose 'Heuristic mode' for target identification
Argument ">TamiR8064%0AGCCAACTGAGCTATTCCAGC%0" isn't numeric in bitwise and (&) at /data1/masw/bowtie2-2.3.1-legacy/bowtie2 line 551, <BT> line 4.
Argument ">TamiR8064%0AGCCAACTGAGCTATTCCAGC%0" isn't numeric in bitwise and (&) at /data1/masw/bowtie2-2.3.1-legacy/bowtie2 line 551, <BT> line 6.
Argument ">TamiR8064%0AGCCAACTGAGCTATTCCAGC%0" isn't numeric in bitwise and (&) at /data1/masw/bowtie2-2.3.1-legacy/bowtie2 line 551, <BT> line 8.
Argument ">TamiR8064%0AGCCAACTGAGCTATTCCAGC%0" isn't numeric in bitwise and (&) at /data1/masw/bowtie2-2.3.1-legacy/bowtie2 line 551, <BT> line 10.
Argument ">TamiR8064%0AGCCAACTGAGCTATTCCAGC%0" isn't numeric in bitwise and (&) at /data1/masw/bowtie2-2.3.1-legacy/bowtie2 line 551, <BT> line 12.
Argument ">TamiR8064%0AGCCAACTGAGCTATTCCAGC%0" isn't numeric in bitwise and (&) at /data1/masw/bowtie2-2.3.1-legacy/bowtie2 line 551, <BT> line 14.
Argument ">TamiR8064%0AGCCAACTGAGCTATTCCAGC%0" isn't numeric in bitwise and (&) at /data1/masw/bowtie2-2.3.1-legacy/bowtie2 line 551, <BT> line 16.
Argument ">TamiR8064%0AGCCAACTGAGCTATTCCAGC%0" isn't numeric in bitwise and (&) at /data1/masw/bowtie2-2.3.1-legacy/bowtie2 line 551, <BT> line 18.
Argument ">TamiR8064%0AGCCAACTGAGCTATTCCAGC%0" isn't numeric in bitwise and (&) at /data1/masw/bowtie2-2.3.1-legacy/bowtie2 line 551, <BT> line 20.
......

**Comment by atulkakrana** [comment]
Hi Shenweima,

You downloaded sPARTA from [Releases](https://github.com/atulkakrana/sPARTA/releases) page right? And not from [Code](https://github.com/atulkakrana/sPARTA) page? If, you are unsure just open the script and check first couple of line if they match with the one [here](https://github.com/atulkakrana/sPARTA/blob/master/sPARTA.py).

Please update your Bowtie (v2) to the latest stable from here: https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.3.2

Atul

**Comment by shenweima** [comment]
The first couple of line in sPARTA.py:
`## sPARTA: small RNA-PARE Target Analyzer public version `
`## Updated: version-1.25 05/13/2017`
`## Author: kakrana@udel.edu`
`## Author: rkweku@udel.edu`

`## Copyright (c): 2016, by University of Delaware`
`##              Contributor : Atul Kakrana`
`##              Affilation  : Meyers Lab (Donald Danforth Plant Science Center, St. Louis, MO)`
`##              License copy: Available at https://opensource.org/licenses/Artistic-2.0`

I will update your Bowtie (v2) to the latest stable now.
It works now

**Comment by atulkakrana** [comment]
Great! I am happy. I will close this issue report.

Atul
