### ISSUE TITLE
How to filter the the result in All.libs.validated.uniq.csv?

### ISSUE THREAD

**Issue by shenweima** [atulkakrana/sPARTA.github#5]
There are many targets in All.libs.validated.uniq.csv. Many columns are list in csv file, but I don't know how to filter the targets. Could you give me some suggestion?
I attach the [result file](https://drive.google.com/open?id=0B2XymiM5C_e5bDlRbmhoS1VCQ3M)

**Comment by atulkakrana** [comment]
I would use:

* ***PARE abundance*** >= 10 (or at least 5)
It corresponds to maximum PARE reads, in one of your library, supporting cleavage site. Higher the better. 

* ***10-nt window abundance*** >= 0.75
It represents noise around cleavage site, a higher ratio suggest that most reads in +/-10nt window correspond to cleavage site. Higher the better.

* ***Score*** <= 5
This is complementarity based penalty score. Lesser the better.

If the results are from tens of PARE libraries, then I would also suggest using corrected *p-value* cutoff <= 0.05. But it's your choice, as you know data better.

Best

Atul

**Comment by shenweima** [comment]
Thank you very much!
