### ISSUE TITLE
ValueError: could not convert string to float: 'AAACTCACTCTGTTCTCTCA'

### ISSUE THREAD

**Issue by Maja-nib** [atulkakrana/sPARTA.github#6]
Dear Atul,

I run your pipeline SPARTA.py with this command:/usr/bin/python3.4 sPARTA.py -featureFile redundant.fa -miRNAFile endogenous_sRNAs.fa -genomeFeature 0 -libs Tally_library1.txt -tarPred -tarScore --tag2FASTA --map2DD --validate 

However the process stopped and the output map is empty, on the other hand the map predicted contains files. The last part that  terminal shows is this:

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "sPARTA.py", line 1821, in validatedTargetsFinder
    categoryList[int(categoryScore)])
  File "sPARTA.py", line 1706, in pValueCalculator
    n = sum(x.count(miRNAName) for x in targetFinderList if float(x[5]) ==
  File "sPARTA.py", line 1706, in <genexpr>
    n = sum(x.count(miRNAName) for x in targetFinderList if float(x[5]) ==
ValueError: could not convert string to float: 'AAACTCACTCTGTTCTCTCA'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sPARTA.py", line 2921, in <module>
    main()
  File "sPARTA.py", line 2872, in main
    validatedTargetsList = PPResults(validatedTargetsFinder, PAGeIndexList)
  File "sPARTA.py", line 1608, in PPResults
    results = (res.get())
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
ValueError: could not convert string to float: 'AAACTCACTCTGTTCTCTCA'

Do you have any idea what could be wrong? Thank you very much. Kind regards. Maja

**Comment by atulkakrana** [comment]
Thanks for using _sPARTA_. I think there is something wrong with miRNA file format. Could you please paste the output of command: 
`head endogenous_sRNAs.fa`

Atul

**Comment by Maja-nib** [comment]
Hello,

I attached the head of miRNA file in FASTA format.
Thank you for your help.

Kind regards,

Maja

___________________________________________________
Maja Križnik
Nacionalni inštitut za biologijo<http://www.nib.si/> / National Institute of Biology<http://www.nib.si/eng/>
Oddelek za biotehnologijo in sistemsko biologijo<http://www.nib.si/oddelki/oddelek-za-biotehnologijo-in-sistemsko-biologijo>
Department of Biotechnology and Systems Biology<http://www.nib.si/eng/index.php/departments/department-of-biotechnology-and-systems-biology>
Večna pot 111, SI-1000 Ljubljana, Slovenia

Phone: + 386 (0)59 232 813
Fax: + 386 (0)1 257 38 47
E-mail: maja.kriznik@nib.si<mailto:maja.kriznik@nib.si>

[cid:image002.png@01D1B29C.4199B610]

**Comment by atulkakrana** [comment]
Hi Maja,

It seems you forgot to attach the file. Can you paste the information here?

Atul

**Comment by rkweku** [comment]
Hi Maja,

I'm actually suspecting that there is a problem with the predicted targets file. Could you also paste the head of the All.targs.parsed.csv file (located in the predicted folder). Index 5 should be the score, but it looks like it is one of the sequences.

**Comment by Maja-nib** [comment]
Hi,

It took a while but I finally, figured out what was wrong. I played with diffferent input sRNAs files and transcriptome files and what I discovered was that the message I got 
ValueError: could not convert string to float: 'AAACTCACTCTGTTCTCTCA' was due to complex header names in my transcriptome fasta file, when I simplified them, everything works.

**Comment by atulkakrana** [comment]
I am happy to know that you successfully investigated and resolved the problem. All the best with you analyses.

Atul
