### ISSUE TITLE
Cutting site for PARE result

### ISSUE THREAD

**Issue by obenno** [atulkakrana/sPARTA.github#7]
Hi Atul,

Thanks for the software~
There is one confusing thing, about of PARE validated cutting site.
In the output file All.libs.validated.uniq.csv, by presenting genomeCleavePosition, do you mean that cleavage site is on the left or right of the reported site? Is it the same with positive and negative strand? Thanks~

Obenno

**Comment by atulkakrana** [comment]
Assuming that miRNA cleaved the RNA transcript (and not genome), the "genomeCleavePosition" refers to 5'-end of the cleaved transcript i.e. 5'-end of PARE reads. So, for genes on "watson" strand is must on left of the cleavage site and for "crick" strand it should be on the right of the cleavage site.  

Atul

**Comment by obenno** [comment]
Thanks a lot ! That will be very helpful~~

Obenno
