### ISSUE TITLE
Update data generated from v1.23

### ISSUE THREAD

**Issue by obenno** [atulkakrana/sPARTA.github#8]
Hi Atul,

I noticed that you have a bug of cleavage site fixed in v1.25. May I ask how could I update result generated from 1.23 to 1.25 instead of rerunning all the steps? Thanks~
Obenno

**Comment by atulkakrana** [comment]
Hi Obenno,

Are you are interested in precise cleavage position? If not, the results from earlier versions are good to use i.e. there will be no difference in target genes for your miRNAs.

Atul

**Comment by obenno** [comment]
Hi Atul,

Thanks~ Yes, I'm interested in precise cleavage site to correlate miRNA targets with predicted PHAS loci.
By the way, I used genome fasta and GFF as input for sPARTA, and then checked result manually by remapping input fasta to genome file with bowite2 (default parameter), and loaded result into IGV to check by eyes. Since there are no read ids in your PAGe result, I can only guess the reads you selected by position and abundance. But for v1.25 result, I still found a 2bp shift in my result, just checked only one record in output...Can we trace the reads responding to cleavage site in output? Many thanks.

Obenno

**Comment by obenno** [comment]
Hi Atul,

Sorry that I didn't provide detail information. I was running sPARTA on rice genome downloaded from phytozome (MSUv7.0), the PARE data is from SRR034102, the miRNA reads is CCTCTACCGCCTCAACGCC. Hope this could help~ 

Obenno

**Comment by atulkakrana** [comment]
Hi Obenno,

> But for v1.25 result, I still found a 2bp shift in my result, just checked only one record in output.

Sorry for late response. I checked the results from latest version (v1.25) and didn't find any 2-nt shift. In fact, I checked several PARE validated targets from genic and intergenic regions on our internal genome viewer and all seem good to me. So the cleavage sites are all accurate. 

Please check the header of `sPARTA.py` file to confirm the version that you are using is latest (v1.25). You can also check through command line:
`head sPARTA.py`

 and it should give you results like this:  
```  
## sPARTA: small RNA-PARE Target Analyzer public version 
## Updated: version-1.25 05/13/2017
## Author: kakrana@udel.edu
## Author: rkweku@udel.edu
```
>I can only guess the reads you selected by position and abundance 

In the "output" folder, both library-specific results and the combined results file, includes PARE read for every validated target under the 'tarSeq' column

I would also suggest you to check the folder 'dd_map'; it includes mapped reads for every library. You might want to combine files that correspond to a single library using `cat` command as there will be multiple files for same PARE library but corresponding to different fragments of the genome.

Let me know if you have more questions.

Atul

**Comment by atulkakrana** [comment]
Obenno,

> I was running sPARTA on rice genome downloaded from phytozome (MSUv7.0), the PARE data is from SRR034102, the miRNA reads is CCTCTACCGCCTCAACGCC.

Please keep in mind that miRNA seq in the results file is reversed i.e. 3'->5' to visually compare with PARE read for matches and mismatches. Sorry that it is not clearly mentioned in our README.

Atul

**Comment by obenno** [comment]
Atul,

I'm really sorry that I confused result with older version and latest v1.25, I only rerun new commands without deleting older PAGe result, although mapping of PARE reads were performed again according to log, it seems still used older PAGe result... After a totally new batch of v1.25, the cleavage site is accurate now. Sorry the inconvenience that cause by my own careless. Thanks again.

Obenno

**Comment by atulkakrana** [comment]
Hi Obenno,

It's OK - I am happy that I checked it again; it's better to be safe than sorry. Anyway, we will push a new update to sPARTA very soon. In this update we are adding PARE read abundances from all libraries to final report and improving compatibility with IGV viewer. So, you don't have to map the PARE libraries again. Keep an eye on our [releases](https://github.com/atulkakrana/sPARTA/releases) page. 

I am closing the this issue/ bug report.

Atul

**Comment by obenno** [comment]
Hi Atul,

Thanks, that's a great news, will keep on watching~

Obenno
